# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64

archives:
- format: tar.gz
  # this name template makes the OS and Arch compatible with the results of `uname`.
  name_template: >-
    {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{-
    else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm
    }}v{{ .Arm }}{{ end }}
  format_overrides:
  - goos: windows
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"

release:
  replace_existing_artifacts: true

kos:
- repository: ghcr.io/pbar1/{{ .ProjectName }}
  tags:
  - latest
  - "{{ .Version }}"
  - "{{ .Major }}.{{ .Minor }}"
  - "{{ .Major }}"
  creation_time: "{{ .CommitTimestamp }}"
  platforms:
  - linux/amd64
  - linux/arm64
  annotations:
    org.opencontainers.image.source: https://github.com/pbar1/{{ .ProjectName }}
    org.opencontainers.image.description: AWS multi-factor authentication manager
    org.opencontainers.image.licenses: MIT

brews:
- homepage: https://github.com/pbar1/{{ .ProjectName }}
  description: AWS multi-factor authentication manager
  test: |
    system "#{bin}/{{ .ProjectName }} version"
  repository:
    owner: pbar1
    name: homebrew-tap
    git:
      url: git@github.com:pbar1/homebrew-tap.git
      private_key: "{{ .Env.HOMEBREW_SSH_KEY }}"

scoops:
- homepage: https://github.com/pbar1/{{ .ProjectName }}
  description: AWS multi-factor authentication manager
  directory: bucket
  repository:
    owner: pbar1
    name: scoop-bucket
    git:
      url: git@github.com:pbar1/scoop-bucket.git
      private_key: "{{ .Env.SCOOP_SSH_KEY }}"

aurs:
- homepage: https://github.com/pbar1/{{ .ProjectName }}
  description: AWS multi-factor authentication manager
  git_url: "ssh://aur@aur.archlinux.org/{{ .ProjectName }}-bin.git"
  private_key: "{{ .Env.AUR_KEY }}"
