project_name: mfaws

before:
  hooks:
    - go mod download

builds:
  -
    binary: '{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

universal_binaries:
  - ids:
      - mfaws
    replace: false

archives:
  -
    format: binary
    name_template: |
      mfaws_
      {{- .Version}}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows{{ end }}_
      {{- .Arch -}}
release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    ids:
    - mfaws
    dockerfile: build/package/Dockerfile
    image_templates:
      - "pbar1/{{ .ProjectName }}:{{ .Tag }}"
      - "pbar1/{{ .ProjectName }}:{{ .Major }}"
      - "pbar1/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "pbar1/{{ .ProjectName }}:latest"
